---
title: "Workshop - I/O and Medication"
author: "Wei-Hung Weng (ckbjimmy [at] mit [dot] edu)"
date: "28 October 2018"
output:
  html_document:
    keep_md: true
  pdf_document: default
subtitle: '2018.HST.953: Collaborative Data Science in Medicine'
---




# Where to find the data


## MIMIC

This paper describes mimiciii: https://www.nature.com/articles/sdata201635

[MIT-LCP/mimic-code](https://github.com/MIT-LCP/mimic-code)
https://github.com/MIT-LCP/mimic-code/tree/master/concepts/durations


## eICU

This paper describes eicu: https://www.nature.com/articles/sdata2018178

[MIT-LCP/eicu-code](https://github.com/MIT-LCP/eicu-code)

eicu-code/concepts/pivoted/pivoted-infusion.sql
eicu-code/concepts/pivoted/pivoted-med.sql
eicu-code/concepts/pivoted/pivoted-treatment-vasopressor.sql
eicu-code/concepts/pivoted/pivoted-uo.sql

https://github.com/MIT-LCP/eicu-code/blob/master/notebooks/allergy.ipynb
https://github.com/MIT-LCP/eicu-code/blob/master/notebooks/infusiondrug.ipynb
https://github.com/MIT-LCP/eicu-code/blob/master/notebooks/intakeoutput.ipynb
https://github.com/MIT-LCP/eicu-code/blob/master/notebooks/medication.ipynb
https://github.com/MIT-LCP/eicu-code/blob/master/notebooks/treatment.ipynb


```{r}
# Establishing GCP connection
library(bigrquery)

project_id <- "hst-953-2018"
options(httr_oauth_cache=FALSE)

run_query <- function(query, max_pages=10000){
  data <- query_exec(query, project=project_id, use_legacy_sql=FALSE, max_pages=100)
  return(data)
}

# test and get auth code
run_query(paste0("SELECT count(1) FROM `physionet-data.mimiciii_demo`.`patients`"))
```

```{r}

# pivoted med
get_sql <- function(f){
  con = file(f, "r")
  sql.string <- ""
  while (TRUE) {
    line <- readLines(con, n=1)
    if (length(line) == 0) {
      break
    }
    line <- gsub("\\t", " ", line)
    if (grepl("--", line) == TRUE) {
      line <- paste(sub("--", "/*", line), "*/")
    }
    sql.string <- paste(sql.string, line)
  }
  close(con)
  return(sql.string)
}
```

```{r eval=F}
install.packages("reticulate")
library(reticulate)
```

```{python eval=F}
import os
import pandas as pd

from google.colab import auth
from google.cloud import bigquery

auth.authenticate_user()

project_id = 'hst-953-2018'
os.environ["GOOGLE_CLOUD_PROJECT"] = project_id

def run_query(query):
  return pd.io.gbq.read_gbq(query, 
                            project_id=project_id, 
                            verbose=False, 
                            configuration={'query':{'useLegacySql': False}})

def get_sql(f):
  file = open(f, 'r')
  s = " ".join(file.readlines())
  return s

df = run_query("SELECT * FROM `physionet-data.mimiciii_demo`.`patients` limit 10")
df

q = get_sql('./sql/bq-eicu-med.sql')
df = run_query(q)
df
```

[colab](https://colab.research.google.com/drive/1HZHT6BUNNoTE89TF09EveRBMeyZfEI-7)

```{r}
# I/O

## MIMIC-III

### Summing up urine output using outputevents

# https://github.com/MIT-LCP/mimic-code/blob/master/concepts/fluid-balance/urine-output.sql
q <- get_sql("sql/bq-mimic-uo.sql")
res <- run_query(q)
head(res)

# https://github.com/MIT-LCP/mimic-code/blob/master/concepts/pivot/pivoted-uo.sql
q <- get_sql("sql/bq-mimic-pivoted-uo.sql")
res <- run_query(q)
head(res)

# crrt duration
# https://github.com/MIT-LCP/mimic-code/blob/master/concepts/durations/crrt-durations.sql
q <- get_sql("sql/bq-mimic-crrt-durations.sql")
res <- run_query(q)
head(res)

## eICU
q <- get_sql("sql/bq-eicu-io.sql")
res <- run_query(q)
head(res)

# eICU infusion pivoted
# https://github.com/MIT-LCP/eicu-code/blob/master/concepts/pivoted/pivoted-infusion.sql
q <- get_sql("sql/bq-eicu-pivoted-infusion.sql")
res <- run_query(q)
head(res)

# Medication
## MIMIC-III
q <- get_sql("sql/bq-mimic-med.sql")
res <- run_query(q)
head(res)

## eICU
q <- get_sql("sql/bq-eicu-med.sql")
res <- run_query(q)
head(res)

q <- get_sql("sql/bq-eicu-pivoted-med.sql")
res <- run_query(q)
head(res)

```

